(* open Tester *)
(*  *)
(* let edge_test () = *)
(*   (* Test interference graph construction *) *)
(*   let engine f = f in *)
(*   let source_serializer f = igedge2str f in *)
(*   let expected_serializer = igedge2str in *)
(*   let comparer = (=) in *)
(*  *)
(*   let case = test engine source_serializer expected_serializer comparer in *)
(*     print_string "All Tests Passed.\n"; *)
